/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
/**
 *
 * @author cesar
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    private java.awt.CardLayout vistaCards;
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        vistaCards = (java.awt.CardLayout) panelContenido.getLayout();
        
        panelContenido.add(new PanelModuloInicio(), "MODULO_INICIO");
        panelContenido.add(new PanelModuloData(), "MODULO_DATA");
        panelContenido.add(new PanelModuloViajes(), "MODULO_VIAJES");
        vistaCards.show(panelContenido, "MODULO_INICIO");
        
        PanelUserSidebar sidebar = new PanelUserSidebar(this);
        panelSidebarContenedor.setLayout(new java.awt.BorderLayout());
        panelSidebarContenedor.add(sidebar, java.awt.BorderLayout.CENTER);
        
        this.setPreferredSize(new java.awt.Dimension(1100, 700));
        this.setSize(1100, 700);
        this.setLocationRelativeTo(null);
        
        panelSidebarContenedor.revalidate();
        panelSidebarContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebarContenedor = new java.awt.Panel();
        panelContenido = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelSidebarContenedor.setBackground(new java.awt.Color(0, 153, 255));
        panelSidebarContenedor.setPreferredSize(new java.awt.Dimension(220, 700));
        panelSidebarContenedor.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelSidebarContenedor, java.awt.BorderLayout.LINE_START);

        panelContenido.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }
    
    public void navegar(String nombreCard){
        if (vistaCards != null){
            vistaCards.show(panelContenido, nombreCard);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel panelContenido;
    private java.awt.Panel panelSidebarContenedor;
    // End of variables declaration//GEN-END:variables
}
