/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author cesar
 */
public class PanelUserSidebar extends javax.swing.JPanel {
    private FrmPrincipal framePadre;
    /**
     * Creates new form PanelUserSidebar
     */
    public PanelUserSidebar() {
        initComponents();
    }
    
    public PanelUserSidebar(FrmPrincipal padre){
        initComponents();
        this.framePadre=padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioNombre = new javax.swing.JLabel();
        lblUsuarioDNI = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        btnData = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(220, 700));

        lblUsuarioNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuarioNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioNombre.setText("CESAR VILLEGAS");

        lblUsuarioDNI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsuarioDNI.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuarioDNI.setText("61108115");

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setText("INICIO");
        btnInicio.addActionListener(this::btnInicioActionPerformed);

        btnViajes.setBackground(new java.awt.Color(255, 255, 255));
        btnViajes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnViajes.setForeground(new java.awt.Color(0, 0, 0));
        btnViajes.setText("VIAJES");
        btnViajes.addActionListener(this::btnViajesActionPerformed);

        btnData.setBackground(new java.awt.Color(255, 255, 255));
        btnData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnData.setForeground(new java.awt.Color(0, 0, 0));
        btnData.setText("DATA");
        btnData.addActionListener(this::btnDataActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblUsuarioNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblUsuarioDNI)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lblUsuarioNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioDNI)
                .addGap(52, 52, 52)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        if (framePadre != null){
            framePadre.navegar("MODULO_VIAJES");
        }
    }//GEN-LAST:event_btnViajesActionPerformed

    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
        if (framePadre != null){
            framePadre.navegar("MODULO_DATA");
        }
    }//GEN-LAST:event_btnDataActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (framePadre != null){
            framePadre.navegar("MODULO_INICIO");
        }
    }//GEN-LAST:event_btnInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnViajes;
    private javax.swing.JLabel lblUsuarioDNI;
    private javax.swing.JLabel lblUsuarioNombre;
    // End of variables declaration//GEN-END:variables
}
