/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ContenedorControlador;
/**
 *
 * @author GIANCARLO REA
 */
public class PanelContenedor extends javax.swing.JPanel {
    
    ContenedorControlador contenedorServicio;

    public PanelContenedor() {
        initComponents();
        contenedorServicio = new ContenedorControlador();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTara = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPayload = new javax.swing.JTextField();
        btnGuardarContenedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContenedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(810, 540));
        setMinimumSize(new java.awt.Dimension(810, 540));
        setPreferredSize(new java.awt.Dimension(810, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 61, -1));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 30));

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tara:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        txtTara.setBackground(new java.awt.Color(255, 255, 255));
        txtTara.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtTara, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 110, 30));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Payload:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        txtPayload.setBackground(new java.awt.Color(255, 255, 255));
        txtPayload.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPayload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPayload, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, 30));

        btnGuardarContenedor.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardarContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarContenedor.setText("Guardar");
        btnGuardarContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContenedorActionPerformed(evt);
            }
        });
        add(btnGuardarContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 310, -1));

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("REGISTRAR CONTENEDOR");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tblContenedores.setBackground(new java.awt.Color(255, 255, 255));
        tblContenedores.setForeground(new java.awt.Color(0, 0, 0));
        tblContenedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Tara", "Payload"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContenedores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 694, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContenedorActionPerformed
        contenedorServicio.guardarContenedor(txtCodigo.getText(), Double.parseDouble(txtPayload.getText()), Double.parseDouble(txtTara.getText()));
        
        
        
        txtCodigo.setText("");
        txtPayload.setText("");
        txtTara.setText("");
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnGuardarContenedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarContenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContenedores;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPayload;
    private javax.swing.JTextField txtTara;
    // End of variables declaration//GEN-END:variables
}
