/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.BorderFactory;
import servicio.ContenedorServicio;
import javax.swing.table.DefaultTableModel;
import modelo.Contenedor;
import servicio.GestorEquipos;
/**
 *
 * @author GIANCARLO REA
 */
public class PanelContenedor extends javax.swing.JPanel {
    
    ContenedorServicio contenedorServicio;
    DefaultTableModel modelo; 
    private String orden;

    public PanelContenedor() {
        initComponents();
        contenedorServicio = new ContenedorServicio();
        modelo = (DefaultTableModel) tblContenedores.getModel(); 
        this.orden = "default";
        
        actualizarTabla();
        
        txtCodigoBuscado.setVisible(false);
        txtPayloadBuscado_noEncontrado.setVisible(false);
        txtTaraBuscado.setVisible(false);
        
        btnEliminarContenedor.setVisible(false);
        btnLimpiar.setVisible(false);
        btnEditarContenedor.setVisible(false);
        btnGuardarEdicion.setVisible(false);
        
        tblContenedores.setEnabled(false);
    }
    
    public void actualizarTabla() {        
        modelo.setRowCount(0);
        
        switch (this.orden) {
            case "default":
                for (Contenedor c : contenedorServicio.getContenedores()) {
                    Object[] fila = new Object[]{
                        c.getCodigo(),
                        c.getPayload(),
                        c.getTara()
                    };
                    modelo.addRow(fila);
                }
                break;
            case "codigo":
                for (Contenedor c : contenedorServicio.ordenarContenedorPorCodigo()) {
                    Object[] fila = new Object[]{
                        c.getCodigo(),
                        c.getPayload(),
                        c.getTara()
                    };
                    modelo.addRow(fila);
                }
                break;
            case "payload":
                for (Contenedor c : contenedorServicio.ordenarContenedorPorPayload()) {
                    Object[] fila = new Object[]{
                        c.getCodigo(),
                        c.getPayload(),
                        c.getTara()
                    };
                    modelo.addRow(fila);
                }
                break;
            case "tara":
                for (Contenedor c : contenedorServicio.ordenarContenedorPorTara()) {
                    Object[] fila = new Object[]{
                        c.getCodigo(),
                        c.getPayload(),
                        c.getTara()
                    };
                    modelo.addRow(fila);
                }
                break;
            default:
                for (Contenedor c : contenedorServicio.getContenedores()) {
                    Object[] fila = new Object[]{
                        c.getCodigo(),
                        c.getPayload(),
                        c.getTara()
                    };
                    modelo.addRow(fila);
                }
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtContenedorBuscado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTara = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPayload = new javax.swing.JTextField();
        btnGuardarContenedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContenedores = new javax.swing.JTable();
        btnSeleccionarContenedor = new javax.swing.JButton();
        txtTaraBuscado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEliminarContenedor = new javax.swing.JButton();
        btnEditarContenedor = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnOrdenarPorCodigo = new javax.swing.JButton();
        btnOrdenarPorTara = new javax.swing.JButton();
        btnOrdenatPorPayload = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnOrdenarDefault = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtCodigoBuscado = new javax.swing.JTextField();
        txtPayloadBuscado_noEncontrado = new javax.swing.JTextField();
        btnGuardarEdicion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(810, 540));
        setMinimumSize(new java.awt.Dimension(810, 540));
        setPreferredSize(new java.awt.Dimension(810, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 61, -1));

        txtContenedorBuscado.setBackground(new java.awt.Color(255, 255, 255));
        txtContenedorBuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContenedorBuscado.setToolTipText("");
        txtContenedorBuscado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtContenedorBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 200, 30));

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tara:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        txtTara.setBackground(new java.awt.Color(255, 255, 255));
        txtTara.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtTara, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 80, 30));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Payload:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        txtPayload.setBackground(new java.awt.Color(255, 255, 255));
        txtPayload.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPayload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPayload, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 80, 30));

        btnGuardarContenedor.setBackground(new java.awt.Color(51, 153, 255));
        btnGuardarContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarContenedor.setText("Guardar");
        btnGuardarContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContenedorActionPerformed(evt);
            }
        });
        add(btnGuardarContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 140, -1));

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("REGISTRAR CONTENEDOR");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tblContenedores.setBackground(new java.awt.Color(255, 255, 255));
        tblContenedores.setForeground(new java.awt.Color(0, 0, 0));
        tblContenedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Payload", "Tara"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContenedores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 694, 220));

        btnSeleccionarContenedor.setBackground(new java.awt.Color(0, 153, 255));
        btnSeleccionarContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarContenedor.setText("Seleccionar");
        btnSeleccionarContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarContenedorActionPerformed(evt);
            }
        });
        add(btnSeleccionarContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        txtTaraBuscado.setBackground(new java.awt.Color(255, 255, 255));
        txtTaraBuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTaraBuscado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtTaraBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 190, 30));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Ordenar por: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btnEliminarContenedor.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminarContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarContenedor.setText("Eliminar");
        btnEliminarContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContenedorActionPerformed(evt);
            }
        });
        add(btnEliminarContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        btnEditarContenedor.setBackground(new java.awt.Color(255, 153, 0));
        btnEditarContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarContenedor.setText("Editar");
        btnEditarContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContenedorActionPerformed(evt);
            }
        });
        add(btnEditarContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 80, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        btnOrdenarPorCodigo.setBackground(new java.awt.Color(153, 153, 255));
        btnOrdenarPorCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenarPorCodigo.setText("Código");
        btnOrdenarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPorCodigoActionPerformed(evt);
            }
        });
        add(btnOrdenarPorCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        btnOrdenarPorTara.setBackground(new java.awt.Color(153, 204, 255));
        btnOrdenarPorTara.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenarPorTara.setText("Tara");
        btnOrdenarPorTara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPorTaraActionPerformed(evt);
            }
        });
        add(btnOrdenarPorTara, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        btnOrdenatPorPayload.setBackground(new java.awt.Color(255, 153, 153));
        btnOrdenatPorPayload.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenatPorPayload.setText("Payload");
        btnOrdenatPorPayload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenatPorPayloadActionPerformed(evt);
            }
        });
        add(btnOrdenatPorPayload, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ingresar el código del contenedor");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        btnOrdenarDefault.setBackground(new java.awt.Color(0, 153, 255));
        btnOrdenarDefault.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenarDefault.setText("Default");
        btnOrdenarDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarDefaultActionPerformed(evt);
            }
        });
        add(btnOrdenarDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, 30));

        txtCodigoBuscado.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoBuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoBuscado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtCodigoBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 190, 30));

        txtPayloadBuscado_noEncontrado.setBackground(new java.awt.Color(255, 255, 255));
        txtPayloadBuscado_noEncontrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPayloadBuscado_noEncontrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtPayloadBuscado_noEncontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 190, 30));

        btnGuardarEdicion.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardarEdicion.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarEdicion.setText("Guardar");
        btnGuardarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEdicionActionPerformed(evt);
            }
        });
        add(btnGuardarEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContenedorActionPerformed

        contenedorServicio.guardarContenedor(
        txtCodigo.getText(),
        Double.parseDouble(txtPayload.getText()),
        Double.parseDouble(txtTara.getText())
    );

    Contenedor contenedorRegistrado =
            contenedorServicio.obtenerContenedorPörCodigo(txtCodigo.getText());

    GestorEquipos.agregarContenedor(contenedorRegistrado);

    actualizarTabla();

    txtCodigo.setText("");
    txtPayload.setText("");
    txtTara.setText("");
    txtCodigo.requestFocus();

    }//GEN-LAST:event_btnGuardarContenedorActionPerformed

    private void btnSeleccionarContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarContenedorActionPerformed
        String codigo = txtContenedorBuscado.getText(); 
        Contenedor c = contenedorServicio.obtenerContenedorPörCodigo(codigo);
        if (c != null){
            txtPayloadBuscado_noEncontrado.setForeground(Color.BLACK);
            txtPayloadBuscado_noEncontrado.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            
            
            txtCodigoBuscado.setVisible(true);
            txtPayloadBuscado_noEncontrado.setVisible(true);
            txtTaraBuscado.setVisible(true);
            
            btnEliminarContenedor.setVisible(true);
            btnLimpiar.setVisible(true);
            btnEditarContenedor.setVisible(true);
            
            txtContenedorBuscado.setEditable(false);
            txtCodigoBuscado.setEditable(false);
            txtPayloadBuscado_noEncontrado.setEditable(false);
            txtTaraBuscado.setEditable(false);
            
            btnSeleccionarContenedor.setEnabled(false);
            
            txtCodigoBuscado.setText(c.getCodigo());
            txtPayloadBuscado_noEncontrado.setText(String.valueOf(c.getPayload()));
            txtTaraBuscado.setText(String.valueOf(c.getTara()));
            
        } else {
            btnSeleccionarContenedor.setEnabled(false);
            txtContenedorBuscado.setEditable(false);
            
            txtPayloadBuscado_noEncontrado.setVisible(true);
            txtPayloadBuscado_noEncontrado.setEditable(false);
            btnLimpiar.setVisible(true);
            
            txtPayloadBuscado_noEncontrado.setForeground(Color.RED);
            txtPayloadBuscado_noEncontrado.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtPayloadBuscado_noEncontrado.setText("Contenedor No Encontrado");
        }
    }//GEN-LAST:event_btnSeleccionarContenedorActionPerformed

    private void btnEliminarContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContenedorActionPerformed
        contenedorServicio.eliminarContenedor(txtCodigoBuscado.getText());
        
        actualizarTabla();
        
        btnLimpiarActionPerformed(evt);
    }//GEN-LAST:event_btnEliminarContenedorActionPerformed

    private void btnEditarContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContenedorActionPerformed
        txtCodigoBuscado.setEditable(true);
        txtPayloadBuscado_noEncontrado.setEditable(true);
        txtTaraBuscado.setEditable(true);
        
        btnLimpiar.setVisible(false);
        btnEliminarContenedor.setVisible(false);
        
        btnEditarContenedor.setVisible(false);
        btnGuardarEdicion.setVisible(true);
    }//GEN-LAST:event_btnEditarContenedorActionPerformed

    private void btnGuardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEdicionActionPerformed
        String codigo = txtCodigoBuscado.getText();
        double payload = Double.parseDouble(txtPayloadBuscado_noEncontrado.getText());
        double tara = Double.parseDouble(txtTaraBuscado.getText());
        
        contenedorServicio.editarContenedor(codigo, payload, tara);
        
        actualizarTabla();
        
        btnLimpiarActionPerformed(evt);
        btnGuardarEdicion.setVisible(false);
    }//GEN-LAST:event_btnGuardarEdicionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCodigoBuscado.setText("");
        txtPayloadBuscado_noEncontrado.setText("");
        txtTaraBuscado.setText("");
        
        txtCodigoBuscado.setVisible(false);
        txtPayloadBuscado_noEncontrado.setVisible(false);
        txtTaraBuscado.setVisible(false);
        
        txtContenedorBuscado.setText("");
        txtContenedorBuscado.setEditable(true);
        txtContenedorBuscado.requestFocus();
        btnSeleccionarContenedor.setEnabled(true);

        btnLimpiar.setVisible(false);
        btnEditarContenedor.setVisible(false);
        btnEliminarContenedor.setVisible(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnOrdenarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPorCodigoActionPerformed
        this.orden = "codigo";
        actualizarTabla();
    }//GEN-LAST:event_btnOrdenarPorCodigoActionPerformed

    private void btnOrdenatPorPayloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenatPorPayloadActionPerformed
        this.orden = "payload";
        actualizarTabla();
    }//GEN-LAST:event_btnOrdenatPorPayloadActionPerformed

    private void btnOrdenarPorTaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPorTaraActionPerformed
        this.orden = "tara";
        actualizarTabla();
    }//GEN-LAST:event_btnOrdenarPorTaraActionPerformed

    private void btnOrdenarDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarDefaultActionPerformed
        this.orden = "default";
        actualizarTabla();
    }//GEN-LAST:event_btnOrdenarDefaultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarContenedor;
    private javax.swing.JButton btnEliminarContenedor;
    private javax.swing.JButton btnGuardarContenedor;
    private javax.swing.JButton btnGuardarEdicion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOrdenarDefault;
    private javax.swing.JButton btnOrdenarPorCodigo;
    private javax.swing.JButton btnOrdenarPorTara;
    private javax.swing.JButton btnOrdenatPorPayload;
    private javax.swing.JButton btnSeleccionarContenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContenedores;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoBuscado;
    private javax.swing.JTextField txtContenedorBuscado;
    private javax.swing.JTextField txtPayload;
    private javax.swing.JTextField txtPayloadBuscado_noEncontrado;
    private javax.swing.JTextField txtTara;
    private javax.swing.JTextField txtTaraBuscado;
    // End of variables declaration//GEN-END:variables
}
