/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;
import servicio.TerminalServicio;
import modelo.Terminal;

/**
 *
 * @author GIANCARLO REA
 */
public class PanelTerminal extends javax.swing.JPanel {
    TerminalServicio terminalServicio;
    DefaultTableModel modeloTabla;
    /**
     * Creates new form PanelTerminal
     */
    public PanelTerminal() {
        initComponents();
        this.terminalServicio = new TerminalServicio();
        this.modeloTabla = (DefaultTableModel) tblTerminales.getModel();
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        modeloTabla.setRowCount(0);
        
        for(Terminal t: terminalServicio.getTerminales()){
            Object[] fila = new Object[]{
                t.getRuc(),
                t.getNombre(),
                t.getDireccion()
            };
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInputDireccion = new javax.swing.JTextField();
        btnGuardarTerminal = new javax.swing.JButton();
        txtInputRuc = new javax.swing.JTextField();
        txtInputNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTerminales = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(810, 540));
        setMinimumSize(new java.awt.Dimension(810, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRAR TERMINAL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ruc:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        txtInputDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtInputDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtInputDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 420, 30));

        btnGuardarTerminal.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardarTerminal.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarTerminal.setText("Guardar");
        btnGuardarTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTerminalActionPerformed(evt);
            }
        });
        add(btnGuardarTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 131, -1));

        txtInputRuc.setBackground(new java.awt.Color(255, 255, 255));
        txtInputRuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtInputRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, 30));

        txtInputNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtInputNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtInputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 230, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblTerminales.setBackground(new java.awt.Color(255, 255, 255));
        tblTerminales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RUC", "Nombre", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTerminales);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 680, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTerminalActionPerformed
        String ruc = txtInputRuc.getText();
        String nombre = txtInputNombre.getText();
        String direccion = txtInputDireccion.getText();
        terminalServicio.guardarTerminal(ruc, nombre, direccion);
        actualizarTabla();
    }//GEN-LAST:event_btnGuardarTerminalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarTerminal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTerminales;
    private javax.swing.JTextField txtInputDireccion;
    private javax.swing.JTextField txtInputNombre;
    private javax.swing.JTextField txtInputRuc;
    // End of variables declaration//GEN-END:variables
}
