/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.SwingUtilities;

/**
 *
 * @author GIANCARLO REA
 */
public class PanelTractor extends javax.swing.JPanel {

    private boolean formularioVisible = false;

    /**
     * Creates new form PanelTractor
     */
    public PanelTractor() {
        initComponents();
        jSplitPane.setResizeWeight(0);
        panelFormulario.setMinimumSize(new Dimension(0, 0));
        panelTabla.setMinimumSize(new Dimension(0, 0));
        ocultarFormulario();
    }

    private void mostrarFormulario() {
        jSplitPane.setDividerSize(8);
        SwingUtilities.invokeLater(() -> {
            jSplitPane.setDividerLocation(jSplitPane.getHeight() / 3);
        });
        formularioVisible = true;
        btnAgregar.setText("Cerrar formulario");
    }

    private void ocultarFormulario() {
        jSplitPane.setDividerSize(0);
        SwingUtilities.invokeLater(() -> jSplitPane.setDividerLocation(0));
        formularioVisible = false;
        btnAgregar.setText("Agregar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        panelFormulario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelBarra = new javax.swing.JPanel();
        lblTitutlo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(810, 540));
        setMinimumSize(new java.awt.Dimension(810, 540));
        setPreferredSize(new java.awt.Dimension(810, 540));
        setLayout(new java.awt.BorderLayout());

        jSplitPane.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane.setDividerLocation(200);
        jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelFormulario.setBackground(new java.awt.Color(255, 255, 255));
        panelFormulario.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout panelFormularioLayout = new javax.swing.GroupLayout(panelFormulario);
        panelFormulario.setLayout(panelFormularioLayout);
        panelFormularioLayout.setHorizontalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        panelFormularioLayout.setVerticalGroup(
            panelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jSplitPane.setTopComponent(panelFormulario);

        panelTabla.setBackground(new java.awt.Color(255, 255, 255));
        panelTabla.setLayout(new java.awt.BorderLayout());

        jScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(jTable1);

        panelTabla.add(jScrollPane, java.awt.BorderLayout.CENTER);

        panelBarra.setBackground(new java.awt.Color(255, 255, 255));
        panelBarra.setLayout(new java.awt.BorderLayout());

        lblTitutlo.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblTitutlo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitutlo.setText("      TRACTORS");
        panelBarra.add(lblTitutlo, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregar.setBackground(new java.awt.Color(51, 153, 255));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelBotones.add(btnAgregar);

        panelBarra.add(panelBotones, java.awt.BorderLayout.LINE_END);

        panelTabla.add(panelBarra, java.awt.BorderLayout.PAGE_START);

        jSplitPane.setRightComponent(panelTabla);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (formularioVisible) {
            ocultarFormulario();
        } else {
            mostrarFormulario();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitutlo;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPanel panelTabla;
    // End of variables declaration//GEN-END:variables
}
