/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import servicio.ClienteServicio;

/**
 *
 * @author GIANCARLO REA
 */
public class PanelCliente extends javax.swing.JPanel {

    private ClienteServicio clienteServicio;
    private DefaultTableModel modelo;
    private String orden;

    private Cliente clienteSeleccionado;

    public PanelCliente() {
        initComponents();
        clienteServicio = new ClienteServicio(new ArrayList<>());
        modelo = (DefaultTableModel) tblClientes.getModel();
        orden = "default";

        actualizarTabla();
        ocultarEdicion();
        tblClientes.setEnabled(false);
    }

    private void ocultarEdicion() {
        txtRucBuscada.setVisible(false);
        txtNombreBuscado.setVisible(false);
        txtDireccionBuscada.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);

        btnEliminarCliente.setVisible(false);
        btnLimpiarCliente.setVisible(false);
        btnEditarCliente.setVisible(false);
    }

    private void mostrarEdicion() {
        txtRucBuscada.setVisible(true);
        txtNombreBuscado.setVisible(true);
        txtDireccionBuscada.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);

        btnEliminarCliente.setVisible(true);
        btnLimpiarCliente.setVisible(true);
        btnEditarCliente.setVisible(true);
    }

    private void limpiarEdicion() {
        txtRucBuscado.setText("");
        txtRucBuscada.setText("");
        txtNombreBuscado.setText("");
        txtDireccionBuscada.setText("");
        clienteSeleccionado = null;
        ocultarEdicion();
    }

    // Vuelve a llenar la tabla según el orden elegido
    public void actualizarTabla() {
        modelo.setRowCount(0);

        List<Cliente> lista;
        switch (orden) {
            case "ruc":
                lista = clienteServicio.ordenarClientePorRuc();
                break;
            case "nombre":
                lista = clienteServicio.ordenarClientePorNombre();
                break;
            default:
                lista = clienteServicio.getCliente();
                break;
        }

        for (Cliente c : lista) {
            modelo.addRow(new Object[]{c.getRuc(), c.getNombre(), c.getDireccion()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInputRuc = new javax.swing.JTextField();
        txtInputNombre = new javax.swing.JTextField();
        txtInputDireccion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnOrRuc = new javax.swing.JButton();
        btnOrNombre = new javax.swing.JButton();
        btnOrDefault = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRucBuscado = new javax.swing.JTextField();
        btnSelecionarCliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRucBuscada = new javax.swing.JTextField();
        txtNombreBuscado = new javax.swing.JTextField();
        txtDireccionBuscada = new javax.swing.JTextField();
        btnEliminarCliente = new javax.swing.JButton();
        btnLimpiarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(810, 540));
        setMinimumSize(new java.awt.Dimension(810, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRAR CLIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ruc:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección Fiscal:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtInputRuc.setBackground(new java.awt.Color(255, 255, 255));
        txtInputRuc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInputRuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtInputRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 119, -1));

        txtInputNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtInputNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInputNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtInputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 250, -1));

        txtInputDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txtInputDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInputDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtInputDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 370, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 204));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 110, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 153));

        tblClientes.setBackground(new java.awt.Color(255, 255, 255));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RUC", "Nombre", "Direccion Fiscal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 640, 160));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ordenar por:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, -1));

        btnOrRuc.setBackground(new java.awt.Color(204, 102, 255));
        btnOrRuc.setForeground(new java.awt.Color(255, 255, 255));
        btnOrRuc.setText("RUC");
        btnOrRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrRucActionPerformed(evt);
            }
        });
        add(btnOrRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        btnOrNombre.setBackground(new java.awt.Color(255, 102, 102));
        btnOrNombre.setForeground(new java.awt.Color(255, 255, 255));
        btnOrNombre.setText("Nombre");
        btnOrNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrNombreActionPerformed(evt);
            }
        });
        add(btnOrNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        btnOrDefault.setBackground(new java.awt.Color(0, 102, 204));
        btnOrDefault.setForeground(new java.awt.Color(255, 255, 255));
        btnOrDefault.setText("Default");
        btnOrDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrDefaultActionPerformed(evt);
            }
        });
        add(btnOrDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("BUSCAR Y EDITAR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 20));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ruc del Cliente: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 20));

        txtRucBuscado.setBackground(new java.awt.Color(255, 255, 255));
        txtRucBuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRucBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        btnSelecionarCliente.setBackground(new java.awt.Color(0, 102, 204));
        btnSelecionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionarCliente.setText("Seleccionar");
        btnSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ruc");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Direccion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        txtRucBuscada.setBackground(new java.awt.Color(255, 255, 255));
        txtRucBuscada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRucBuscada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        txtNombreBuscado.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreBuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNombreBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));

        txtDireccionBuscada.setBackground(new java.awt.Color(255, 255, 255));
        txtDireccionBuscada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDireccionBuscada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 260, -1));

        btnEliminarCliente.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 80, -1));

        btnLimpiarCliente.setBackground(new java.awt.Color(153, 153, 255));
        btnLimpiarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCliente.setText("Limpiar");
        btnLimpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 80, -1));

        btnEditarCliente.setBackground(new java.awt.Color(255, 204, 51));
        btnEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 80, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 640, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            clienteServicio.guardarCliente(
                    txtInputRuc.getText(),
                    txtInputNombre.getText(),
                    txtInputDireccion.getText());

            actualizarTabla();

            txtInputRuc.setText("");
            txtInputNombre.setText("");
            txtInputDireccion.setText("");
            txtInputRuc.requestFocus();

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOrRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrRucActionPerformed
        orden = "ruc";
        actualizarTabla();
    }//GEN-LAST:event_btnOrRucActionPerformed

    private void btnOrNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrNombreActionPerformed
        orden = "nombre";
        actualizarTabla();
    }//GEN-LAST:event_btnOrNombreActionPerformed

    private void btnOrDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrDefaultActionPerformed
        orden = "default";
        actualizarTabla();
    }//GEN-LAST:event_btnOrDefaultActionPerformed

    private void btnSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarClienteActionPerformed
        String ruc = txtRucBuscado.getText().trim();
        clienteSeleccionado = clienteServicio.obtenerClientePorRuc(ruc);

        if (clienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "No existe un cliente con ese RUC",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            limpiarEdicion();
            return;
        }

        txtRucBuscada.setText(clienteSeleccionado.getRuc());
        txtRucBuscada.setEditable(false); // el RUC es la clave, no se edita
        txtNombreBuscado.setText(clienteSeleccionado.getNombre());
        txtDireccionBuscada.setText(clienteSeleccionado.getDireccion());
        mostrarEdicion();

    }//GEN-LAST:event_btnSelecionarClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        if (clienteSeleccionado == null) {
            return;
        }
        try {
            clienteServicio.editarCliente(
                    clienteSeleccionado.getRuc(),
                    txtNombreBuscado.getText(),
                    txtDireccionBuscada.getText());
            actualizarTabla();
            limpiarEdicion();
            JOptionPane.showMessageDialog(this, "Cliente actualizado");
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnLimpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarClienteActionPerformed
        limpiarEdicion();
    }//GEN-LAST:event_btnLimpiarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        if (clienteSeleccionado == null) {
            return;
        }
        int op = JOptionPane.showConfirmDialog(this, "¿Eliminar este cliente?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            clienteServicio.eliminarCliente(clienteSeleccionado.getRuc());
            actualizarTabla();
            limpiarEdicion();
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiarCliente;
    private javax.swing.JButton btnOrDefault;
    private javax.swing.JButton btnOrNombre;
    private javax.swing.JButton btnOrRuc;
    private javax.swing.JButton btnSelecionarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtDireccionBuscada;
    private javax.swing.JTextField txtInputDireccion;
    private javax.swing.JTextField txtInputNombre;
    private javax.swing.JTextField txtInputRuc;
    private javax.swing.JTextField txtNombreBuscado;
    private javax.swing.JTextField txtRucBuscada;
    private javax.swing.JTextField txtRucBuscado;
    // End of variables declaration//GEN-END:variables
}
